import { expect, test } from '@playwright/test'

test('map keeps amenity filters fully inside the white header', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/groc-movera/map?destination=la-marsa')

  await expect(page.getByTestId('page-map')).toBeVisible()
  await expect(page.locator('.app-shell--guest > .app-shell__nav')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Retour à l’accueil' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Filtres' })).toBeVisible()
  await expect(page.getByTestId('map-property-filters')).toHaveCount(0)

  const header = page.locator('.b225-map-top')
  const toolbar = page.locator('.map-search-filter-stack__toolbar')
  const searchPill = page.locator('.map-search-filter-stack__search-pill')
  const amenityFilters = page.getByTestId('map-amenity-filters')
  const stage = page.locator('.b225-map-stage')
  const engine = page.getByTestId('map-engine')
  const surface = page.getByTestId('map-surface')

  await expect(searchPill).toContainText('Logements à La Marsa')
  await expect(searchPill).not.toContainText('Dates')
  await expect(searchPill).not.toContainText('Voyageurs')
  await expect(header.getByText('Appartement', { exact: true })).toHaveCount(0)
  await expect(header.getByText('Villa', { exact: true })).toHaveCount(0)
  await expect(header.getByText('Hôtel', { exact: true })).toHaveCount(0)
  await expect(header.getByText('Maison d’hôte', { exact: true })).toHaveCount(0)
  await expect(header.getByText('Plage', { exact: true })).toHaveCount(0)
  await expect(amenityFilters.locator('[data-filter-id]')).toHaveCount(6)
  await expect(amenityFilters.locator('[data-filter-id="tv"]')).toContainText('TV')
  await expect(amenityFilters.locator('.map-filter-chip__icon')).toHaveCount(0)
  await expect(stage).toHaveCSS('overflow', 'hidden')
  await expect(engine).toHaveCSS('overflow', 'hidden')

  const headerBox = await header.boundingBox()
  const toolbarBox = await toolbar.boundingBox()
  const searchBox = await searchPill.boundingBox()
  const amenityBox = await amenityFilters.boundingBox()
  const stageBox = await stage.boundingBox()
  const surfaceBox = await surface.boundingBox()

  expect(headerBox).not.toBeNull()
  expect(toolbarBox).not.toBeNull()
  expect(searchBox).not.toBeNull()
  expect(amenityBox).not.toBeNull()
  expect(stageBox).not.toBeNull()
  expect(surfaceBox).not.toBeNull()
  expect(headerBox.height).toBeLessThanOrEqual(120)
  expect(searchBox.height).toBeLessThanOrEqual(48)
  expect(searchBox.width).toBeGreaterThan(275)
  expect(amenityBox.y).toBeGreaterThan(toolbarBox.y + toolbarBox.height)
  expect(amenityBox.y + amenityBox.height).toBeLessThanOrEqual(headerBox.y + headerBox.height)
  expect(Math.abs(stageBox.y - (headerBox.y + headerBox.height))).toBeLessThanOrEqual(2)
  expect(Math.abs(surfaceBox.y - stageBox.y)).toBeLessThanOrEqual(2)
  expect(Math.abs((headerBox.height + stageBox.height) - 844)).toBeLessThanOrEqual(3)
  await expect(header).toHaveCSS('background-color', 'rgba(254, 254, 253, 0.86)')

  const firstAmenity = amenityFilters.locator('[data-filter-id]').first()
  const amenityChipBox = await firstAmenity.boundingBox()
  expect(amenityChipBox).not.toBeNull()
  expect(amenityChipBox.height).toBeLessThanOrEqual(48)

  await page.getByRole('button', { name: 'Retour à l’accueil' }).click()
  await expect(page.getByTestId('page-home')).toBeVisible()
  await expect(page).toHaveURL(/\/groc-movera\/?$/)
})

test('map header remains contained on a narrow phone', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('/groc-movera/map')

  const header = page.locator('.b225-map-top')
  const filters = page.getByTestId('map-amenity-filters')
  const stage = page.locator('.b225-map-stage')
  const headerBox = await header.boundingBox()
  const filtersBox = await filters.boundingBox()
  const stageBox = await stage.boundingBox()

  expect(headerBox).not.toBeNull()
  expect(filtersBox).not.toBeNull()
  expect(stageBox).not.toBeNull()
  expect(filtersBox.y + filtersBox.height).toBeLessThanOrEqual(headerBox.y + headerBox.height)
  expect(Math.abs(stageBox.y - (headerBox.y + headerBox.height))).toBeLessThanOrEqual(2)
  expect(headerBox.height).toBeLessThanOrEqual(120)

  const firstAmenity = filters.locator('[data-filter-id]').first()
  const chipBox = await firstAmenity.boundingBox()
  expect(chipBox).not.toBeNull()
  expect(chipBox.height).toBeLessThanOrEqual(48)
})

test('bottom navigation remains available outside the map', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/groc-movera/')

  await expect(page.getByTestId('page-home')).toBeVisible()
  await expect(page.locator('.app-shell--guest > .app-shell__nav')).toBeVisible()
})
