const items = (group, entries) => entries.map(([id, label, detail]) => ({ id, label, group, ...(detail ? { detail } : {}) }))

export const HOTEL_AMENITY_GROUPS = Object.freeze([
  { id: 'hotel-room', label: 'Chambre & confort', hotelOnly: true },
  { id: 'hotel-bath', label: 'Salle de bain', hotelOnly: true },
  { id: 'hotel-reception', label: 'Réception & accueil', hotelOnly: true },
  { id: 'hotel-housekeeping', label: 'Ménage & blanchisserie', hotelOnly: true },
  { id: 'hotel-food', label: 'Restauration & boissons', hotelOnly: true },
  { id: 'hotel-wellness', label: 'Piscine, spa & sport', hotelOnly: true },
  { id: 'hotel-business', label: 'Travail & événements', hotelOnly: true },
  { id: 'hotel-family', label: 'Famille & divertissement', hotelOnly: true },
  { id: 'hotel-transport', label: 'Parking & transport', hotelOnly: true },
  { id: 'hotel-accessibility', label: 'Accessibilité', hotelOnly: true },
  { id: 'hotel-security', label: 'Sécurité', hotelOnly: true },
  { id: 'hotel-hostel', label: 'Hostel & espaces partagés', hotelOnly: true },
  { id: 'hotel-outdoor', label: 'Extérieurs & loisirs', hotelOnly: true },
  { id: 'hotel-sustainability', label: 'Services durables', hotelOnly: true },
])

export const HOTEL_AMENITIES = Object.freeze([
  ...items('hotel-room', [
    ['hotel-room-service', 'Service en chambre'],
    ['hotel-minibar', 'Minibar'],
    ['hotel-kettle', 'Bouilloire'],
    ['hotel-room-safe', 'Coffre-fort en chambre'],
    ['hotel-blackout-curtains', 'Rideaux occultants'],
    ['hotel-soundproofing', 'Insonorisation'],
    ['hotel-smart-tv', 'Smart TV'],
    ['hotel-streaming', 'Services de streaming'],
    ['hotel-telephone', 'Téléphone en chambre'],
    ['hotel-desk', 'Bureau en chambre'],
    ['hotel-balcony', 'Balcon privé'],
    ['hotel-room-terrace', 'Terrasse privée'],
    ['hotel-hypoallergenic-bedding', 'Literie hypoallergénique'],
    ['hotel-pillow-menu', 'Menu d’oreillers'],
    ['hotel-bottled-water', 'Eau en bouteille'],
    ['hotel-coffee-tea', 'Café & thé en chambre'],
    ['hotel-usb-outlets', 'Prises USB / USB-C'],
    ['hotel-wakeup-alarm', 'Réveil / alarme'],
  ]),
  ...items('hotel-bath', [
    ['hotel-bathrobe', 'Peignoir'],
    ['hotel-slippers', 'Chaussons'],
    ['hotel-premium-toiletries', 'Produits d’accueil'],
    ['hotel-bathtub', 'Baignoire'],
    ['hotel-walkin-shower', 'Douche à l’italienne'],
    ['hotel-bidet', 'Bidet'],
    ['hotel-towel-warmer', 'Sèche-serviettes'],
    ['hotel-magnifying-mirror', 'Miroir grossissant'],
    ['hotel-dental-kit', 'Kit dentaire'],
    ['hotel-shaving-kit', 'Kit de rasage'],
  ]),
  ...items('hotel-reception', [
    ['hotel-reception-24h', 'Réception 24h/24'],
    ['hotel-concierge', 'Conciergerie'],
    ['hotel-luggage-storage', 'Bagagerie'],
    ['hotel-express-checkin', 'Check-in express'],
    ['hotel-express-checkout', 'Check-out express'],
    ['hotel-early-checkin', 'Arrivée anticipée'],
    ['hotel-late-checkout', 'Départ tardif'],
    ['hotel-wakeup-service', 'Service de réveil'],
    ['hotel-currency-exchange', 'Change de devises'],
    ['hotel-tour-desk', 'Bureau d’excursions'],
    ['hotel-ticket-service', 'Billetterie'],
    ['hotel-multilingual-staff', 'Personnel multilingue'],
    ['hotel-keycard-access', 'Accès par carte'],
  ]),
  ...items('hotel-housekeeping', [
    ['hotel-daily-housekeeping', 'Ménage quotidien'],
    ['hotel-linen-change', 'Changement de linge'],
    ['hotel-towel-change', 'Changement de serviettes'],
    ['hotel-laundry-service', 'Service de blanchisserie'],
    ['hotel-ironing-service', 'Service de repassage'],
    ['hotel-dry-cleaning', 'Nettoyage à sec'],
    ['hotel-shoe-shine', 'Cirage de chaussures'],
  ]),
  ...items('hotel-food', [
    ['hotel-breakfast', 'Petit-déjeuner'],
    ['hotel-breakfast-buffet', 'Petit-déjeuner buffet'],
    ['hotel-restaurant', 'Restaurant'],
    ['hotel-bar', 'Bar'],
    ['hotel-cafe', 'Café'],
    ['hotel-snack-bar', 'Snack-bar'],
    ['hotel-food-room-service', 'Restauration en chambre'],
    ['hotel-vending-machine', 'Distributeurs automatiques'],
    ['hotel-packed-lunch', 'Panier-repas'],
    ['hotel-special-diets', 'Menus diététiques'],
    ['hotel-shared-kitchen', 'Cuisine commune'],
    ['hotel-halal-options', 'Options halal'],
    ['hotel-vegetarian-options', 'Options végétariennes'],
  ]),
  ...items('hotel-wellness', [
    ['hotel-indoor-pool', 'Piscine intérieure'],
    ['hotel-outdoor-pool', 'Piscine extérieure'],
    ['hotel-rooftop-pool', 'Piscine sur le toit'],
    ['hotel-kids-pool', 'Piscine enfants'],
    ['hotel-spa', 'Spa'],
    ['hotel-sauna', 'Sauna'],
    ['hotel-hammam', 'Hammam'],
    ['hotel-massage', 'Massages'],
    ['hotel-beauty-salon', 'Salon de beauté'],
    ['hotel-yoga', 'Yoga'],
    ['hotel-personal-trainer', 'Coach sportif'],
    ['hotel-fitness-24h', 'Salle de sport 24h/24'],
  ]),
  ...items('hotel-business', [
    ['hotel-business-center', 'Business center'],
    ['hotel-coworking', 'Espace coworking'],
    ['hotel-meeting-rooms', 'Salles de réunion'],
    ['hotel-conference-room', 'Salle de conférence'],
    ['hotel-banquet-hall', 'Salle de réception'],
    ['hotel-printing-service', 'Impression / photocopie'],
    ['hotel-projector', 'Vidéoprojecteur'],
    ['hotel-event-space', 'Espace événementiel'],
  ]),
  ...items('hotel-family', [
    ['hotel-kids-club', 'Club enfants'],
    ['hotel-playground', 'Aire de jeux'],
    ['hotel-babysitting', 'Garde d’enfants'],
    ['hotel-family-rooms', 'Chambres familiales'],
    ['hotel-board-games', 'Jeux de société'],
    ['hotel-games-room', 'Salle de jeux'],
    ['hotel-library', 'Bibliothèque'],
    ['hotel-cinema-room', 'Salle cinéma'],
    ['hotel-live-entertainment', 'Animations / spectacles'],
    ['hotel-pet-friendly', 'Animaux acceptés'],
  ]),
  ...items('hotel-transport', [
    ['hotel-airport-shuttle', 'Navette aéroport'],
    ['hotel-private-shuttle', 'Navette privée'],
    ['hotel-valet-parking', 'Voiturier'],
    ['hotel-garage', 'Garage'],
    ['hotel-car-rental', 'Location de voiture'],
    ['hotel-bike-rental', 'Location de vélos'],
    ['hotel-taxi-service', 'Service taxi'],
    ['hotel-accessible-parking', 'Parking PMR'],
  ]),
  ...items('hotel-accessibility', [
    ['hotel-elevator', 'Ascenseur'],
    ['hotel-wheelchair-access', 'Accès fauteuil roulant'],
    ['hotel-accessible-rooms', 'Chambres PMR'],
    ['hotel-rollin-shower', 'Douche accessible'],
    ['hotel-grab-rails', 'Barres d’appui'],
    ['hotel-lowered-sink', 'Lavabo abaissé'],
    ['hotel-tactile-signage', 'Signalétique tactile'],
    ['hotel-hearing-accessibility', 'Équipements malentendants'],
  ]),
  ...items('hotel-security', [
    ['hotel-security-24h', 'Sécurité 24h/24'],
    ['hotel-cctv-common', 'Vidéosurveillance espaces communs'],
    ['hotel-fire-extinguishers', 'Extincteurs'],
    ['hotel-smoke-detectors', 'Détecteurs de fumée'],
    ['hotel-first-aid', 'Trousse de premiers secours'],
    ['hotel-emergency-exits', 'Sorties de secours'],
    ['hotel-keycard-security', 'Contrôle d’accès électronique'],
  ]),
  ...items('hotel-hostel', [
    ['hotel-dorm-mixed', 'Dortoir mixte'],
    ['hotel-dorm-female', 'Dortoir femmes'],
    ['hotel-privacy-curtains', 'Rideaux de confidentialité'],
    ['hotel-bunk-bed', 'Lits superposés'],
    ['hotel-bed-reading-light', 'Lampe de lecture individuelle'],
    ['hotel-bed-power-outlet', 'Prise individuelle au lit'],
    ['hotel-personal-locker', 'Casier personnel'],
    ['hotel-shared-lounge', 'Salon commun'],
    ['hotel-hostel-kitchen', 'Cuisine partagée hostel'],
    ['hotel-hostel-laundry', 'Laverie voyageurs'],
    ['hotel-social-events', 'Événements sociaux'],
    ['hotel-luggage-room', 'Local à bagages'],
    ['hotel-hostel-coworking', 'Espace travail partagé'],
    ['hotel-hostel-bar', 'Bar / espace social'],
  ]),
  ...items('hotel-outdoor', [
    ['hotel-garden', 'Jardin'],
    ['hotel-rooftop', 'Rooftop'],
    ['hotel-sun-terrace', 'Terrasse ensoleillée'],
    ['hotel-picnic-area', 'Aire de pique-nique'],
    ['hotel-bbq', 'Barbecue'],
    ['hotel-private-beach', 'Plage privée'],
    ['hotel-beach-service', 'Service de plage'],
    ['hotel-sunbeds', 'Transats'],
    ['hotel-umbrellas', 'Parasols'],
    ['hotel-water-sports', 'Sports nautiques'],
  ]),
  ...items('hotel-sustainability', [
    ['hotel-refill-water', 'Fontaine / recharge d’eau'],
    ['hotel-recycling', 'Tri & recyclage'],
    ['hotel-no-single-use-plastic', 'Sans plastique à usage unique'],
    ['hotel-energy-saving', 'Équipements basse consommation'],
    ['hotel-solar-energy', 'Énergie solaire'],
    ['hotel-local-products', 'Produits locaux'],
    ['hotel-towel-reuse', 'Programme réutilisation serviettes'],
  ]),
])


const COMMON_AMENITY_LABELS = Object.freeze({
  wifi: 'Wi-Fi haut débit',
  parking: 'Parking privé',
  ac: 'Climatisation',
  kitchen: 'Cuisine équipée',
  tv: 'Télévision',
  pool: 'Piscine',
  waterfront: 'Bord de mer',
  'beach-access': 'Accès plage',
  outdoor: 'Mobilier de terrasse',
  gym: 'Espace fitness',
  workspace: 'Coin bureau',
  heating: 'Chauffage',
  'hot-water': 'Eau chaude',
  refrigerator: 'Réfrigérateur',
  washer: 'Lave-linge',
  dryer: 'Sèche-linge',
  'coffee-maker': 'Machine à café',
  essentials: 'Linge & essentiels',
})

const AMENITY_BY_ID = new Map([
  ...Object.entries(COMMON_AMENITY_LABELS).map(([id, label]) => [id, { id, label }]),
  ...HOTEL_AMENITIES.map((item) => [item.id, item]),
])

export function listingAmenityLabel(id, fallback = '') {
  return AMENITY_BY_ID.get(id)?.label || fallback || id
}

export function listingAmenityLabels(ids) {
  return (Array.isArray(ids) ? ids : []).map((id) => listingAmenityLabel(id)).filter(Boolean)
}
